Add devcontainer configuration, enable cross-platform builds, fix test
hendrikmaus/helm-templexer pull request #94
Opened 2022-08-25 09:32 UTC by chriscunningham-trivago

-   Add a Visual Studio Code devcontainer configuration, which contains all dependencies required to build the package on both x86_64 and arm64.
-   Add the MIT license text, inferred from the license the crate has on crates.io.
-   Update the matrix used in GitHub Actions to build across four different architectures (Darwin and Linux, x86_64 and arm64).
-   Annotate currently-unused code to stop the Clippy test from failing.

2022-08-25 10:12 UTC, AlexanderThaller requested changes

2022-08-25 10:12 UTC, AlexanderThaller commented on .devcontainer/Dockerfile
> +RUN rustup target add \
```suggestion
RUN "${HOME}/.cargo/bin/rustup" target add \
```

Else I get an error about `rustup` not being found on my machine. I think something with updating `PATH` isn't working.

```
Step 7/7 : RUN rustup target add   aarch64-unknown-linux-gnu   x86_64-unknown-linux-gnu
 ---> Running in b84c45bf2a3d
/bin/sh: 1: rustup: not found
The command '/bin/sh -c rustup target add   aarch64-unknown-linux-gnu   x86_64-unknown-linux-gnu' returned a non-zero code: 127
```

2022-08-25 10:12 UTC, AlexanderThaller commented on .cargo/config.toml
> +linker = "x86_64-linux-gnu-gcc"
Can we add this file only to the docker container? This breaks building the project on the host machine when the gnu-gcc compiler isn't installed.

```
error: linker `x86_64-linux-gnu-gcc` not found
  |
  = note: No such file or directory (os error 2)
```

2022-08-25 10:12 UTC, AlexanderThaller commented on LICENSE
> +Copyright (c) 2022 [fullname]
```suggestion
Copyright (c) 2022 [Hendrik Maus <aidentailor@gmail.com>]
```

2022-08-25 10:13 UTC, hendrikmaus commented
Thanks for the change-set. Will have a look before end of day.

2022-08-25 11:03 UTC, hendrikmaus commented
Thanks for the review @AlexanderThaller - I have nothing to add 😇

2022-08-26 15:26 UTC, hendrikmaus approved these changes

2022-08-26 15:26 UTC, merged